spring:
  application:
    name: aspire-user
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://ec2-18-219-90-183.us-east-2.compute.amazonaws.com/eureka}
    instance:
      preferIpAddress: true