logging:
  config: config/logback.xml

spring:
  application:
    name: aspire-user
server:
  port: 8780
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true