logging:
  config: config/logback.xml

spring:
  application:
    name: aspire-user
server:
  port: 8780
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://ec2-13-59-206-194.us-east-2.compute.amazonaws.com/eureka}
    instance:
      preferIpAddress: true